### ISSUE TITLE
problem testing the submission

### ISSUE THREAD

**Issue by AnastaseAlex** [ramp-kits/storm_forecast#11]
FileNotFoundError: [Errno 2] No such file or directory: '/home/aaclod/storm_forecast/submissions/starting_kit_pressure_map/problem.py'

We did not expect to have to port the problem.py in each submission. Is this normal?

**Comment by AnastaseAlex** [comment]
Found the solution:
Do not move from the main folder, but add the --sumbission option when running ramp_test_submission.

**Comment by aboucaud** [comment]
Yes the adequate command line is
```bash
ramp_test_submission --submission my_submission
```
where the submission files are in the folder `storm_forcast/submissions/my_submission`.
